Resources:
  UploadPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: JisuiHubPolicy
      Groups:
        - !Ref Group
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - s3:ListBucket
            Resource:
              - arn:aws:s3:::masarakki
          - Effect: Allow
            Action:
              - s3:ListObjectsV2
              - s3:GetObject
              - s3:PutObject
            Resource:
              - arn:aws:s3:::masarakki/Dojin/*
  Group:
    Type: AWS::IAM::Group
  Tadd:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - !Ref Group
  TaddAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref Tadd
Outputs:
  TaddSecret:
    Value: !GetAtt TaddAccessKey.SecretAccessKey
