Resources:
  UploadPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: JisuiHubPolicy
      Groups:
        - !Ref Group
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource:
              - arn:aws:s3:::masarakki/Dojin/*
  Group:
    Type: AWS::IAM::Group
